kalshi:
  base_url: "https://api.elections.kalshi.com"
  locations:
    MIA:
      event-prefix: "KXHIGHMIA-"
    KNYC:
      event-prefix: "KXHIGHNY-"
    KAUS:
      event-prefix: "KXHIGHAUS-"
    KDEN:
      event-prefix: "KXHIGHDEN-"
    KLAX:
      event-prefix: "KXHIGHLAX-"
    KMDW:
      event-prefix: "KXHIGHCHI-"
    KPHL:
      event-prefix: "KXHIGHPHIL-"
    
